title: Harry Scholes
description: Me, on the internet

baseurl: ""
url: "https://harryscholes.github.io"

author:
  name: Harry Scholes
  email: "harryscholes@gmail.com"
  phone: +447849374431
  github: harryscholes
  twitter: harryscholes
  linkedin: harryscholes
  stackoverflow: 5049524/harryscholes
  snapchat: harry.scholes
  instagram: harry.scholes
  scholar: jKGXyxcAAAAJ



# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - /tmp/
  - config.ru
